import Head from "next/head";

import { Inter } from "next/font/google";

import Link from "next/link";

import { useEffect,useState } from "react";
import BlogItem from "./blogitem";
import Loader from "./Loader";



const inter = Inter({ subsets: ["latin"] });

export default function Home() {
 const [blog,setBlog] = useState([])
 const [loading,setLoading] = useState(true)
  
  useEffect(()=>{
    fetch('/api/new-blog').then(res=>res.json())
    .then(data=>setBlog(data))
    setLoading(false)
  },[])
  if(loading){
   return <Loader/>
  }
else{

  if(blog.length === 0){
    return (
    <div className="h-[100vh] flex justify-center items-center flex-col gap-10">
    <h1 className="text-center text-3xl   text-pink-400">No Blog Found</h1>
    <Link className="bg-pink-400 text-white rounded-xl px-5 py-3 " href={'/addblog'}>Create Blog</Link>
    </div>
    )
  }
  else{
    return (
      <div >
        <Head>
          <title>Insane blogs</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
          <link
            href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap"
            rel="stylesheet"
          ></link>
        </Head>
       
       <h1 className="mx-[37rem]  pt-20  text-pink-600 font-bold text-xl">Insane Blog</h1>
        <br />
        <br />
        <div className="flex gap-7 ml-20 mr-9 flex-wrap">
       {blog && blog.map((item)=>{
        const {title,image,_id,description} = item
       
          return(
            <BlogItem title={title} image={image} id={_id} description={description
            }/>
          )
       })}
        </div>
      </div>
    );
  }
}
}